from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('contact', views.contact, name="contact"),
    path('about', views.about, name="about"),
    path('services', views.services, name="services"),
    path('appointment', views.appointment, name="appointment"),
    path('terms', views.terms, name="terms"),
    path('locations', views.locations, name="locations"),
    path('privacy', views.privacy, name="privacy"),
    path('services/dental-bonding', views.dentalbonding, name="dental-bonding"),
    path('services/dental-bridges', views.dentalbridges, name="dental-bridges"),
    path('services/dental-checkup', views.dentalcheckup, name="dental-checkup"),
    path('services/dental-crowns', views.dentalcrowns, name="dental-crowns"),
    path('services/dental-implants', views.dentalimplants, name="dental-implants"),
    path('services/dental-invisalign', views.dentalinvisalign, name="dental-invisalign"),
    path('services/partial-dentures', views.partialdentures, name="partial-dentures"),
    path('services/dental-teeth-whitening', views.dentalteethwhitening, name="dental-teeth-whitening"),
    path('services/dental-white-composite-fillings', views.dentalwhitecompositefillings, name="dental-white-composite-fillings"),
    path('services/wisdom-teeth-removal', views.wisdomteethremoval, name="wisdom-teeth-removal"),
    path('services/dental-smile-imaging-technology', views.dentalsmileimagingtechnology, name="dental-smile-imaging-technology"),
    path('services/general-dentistry', views.generaldentistry, name="general-dentistry"),
    path('locations/east-colfax-avenue', views.eastcolfaxavenue, name="east-colfax-avenue"),
    path('locations/South-Broadway', views.SouthBroadway, name="South-Broadway"),
    path('locations/Larimer-Street', views.LarimerStreet, name="Larimer-Street"),
    path('locations/Antique-Row', views.AntiqueRow, name="Antique-Row"),
    path('locations/Humboldt-Street', views.HumboldtStreet, name="Humboldt-Street"),
    path('locations/16th-St-Mall', views.thStMall, name="16th-St-Mall"),
    path('locations/Speer-Boulevard', views.SpeerBoulevard, name="Speer-Boulevard"),
    path('locations/Welton-Street', views.WeltonStreet, name="Welton-Street"),
    path('locations/South-Gaylord-Street', views.SouthGaylordStreet, name="South-Gaylord-Street"),
    path('locations/east-colfax-avenue/dental-bonding-service', views.dentalbondingservice, name="dental-bonding-service"),
    path('locations/east-colfax-avenue/dental-bridges-service', views.dentalbridgesservice, name="dental-bridges-service"),
    path('locations/east-colfax-avenue/dental-checkup-service', views.dentalcheckupservice, name="dental-checkup-service"),
    path('locations/east-colfax-avenue/dental-crowns-service', views.dentalcrownsservice, name="dental-crowns-service"),
    path('locations/east-colfax-avenue/dental-implants-service', views.dentalimplantsservice, name="dental-implants-service"),
    path('locations/east-colfax-avenue/dental-invisalign-service', views.dentalinvisalignservice, name="dental-invisalign-service"),
    path('locations/east-colfax-avenue/partial-dentures-service', views.partialdenturesser, name="partial-dentures-service"),
    path('locations/east-colfax-avenue/dental-teeth-whitening-service', views.dentalteethwhiteningser, name="dental-teeth-whitening-service"),
    path('locations/east-colfax-avenue/dental-white-composite-fillings-service', views.dentalwhitefillingsser, name="dental-white-composite-fillings-service"),
    path('locations/east-colfax-avenue/wisdom-teeth-removal-service', views.wisdomteethremovalser, name="wisdom-teeth-removal-service"),
    path('locations/east-colfax-avenue/smile-imaging-technology-service', views.smileimagitechser, name="smile-imaging-technology-service"),
    path('locations/east-colfax-avenue/general-dentistry-service', views.generaldentistryser, name="general-dentistry-service"),
    
    ]
